export const UNIDADES = [
  {
    id: "apartamento",
    title: "Apartamento",
    subtitle: "Para 2-3 personas",
    info: "Habitación de 25m² construida en una planta. Cuenta con sommier doble, baño privado, pequeña galería, cochera cubierta con media sombra y asador con parrilla.",
    equipment: [
      { name: 'Smart TV 50"', icon: "Tv" },
      { name: "Vajilla", icon: "Coffee" },
      { name: "Heladera bajo mesada", icon: "Refrigerator" },
      { name: "Microondas", icon: "Microwave" },
      { name: "Pava eléctrica", icon: "Kettle" },
      { name: "Tender", icon: "Shirt" },
    ],
    folder: "apart",
    images: [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.jpg",
      "15.jpg",
      "16.jpg",
      "17.jpg",
    ],

    links: {
      turismomax: "https://turismomax.com/nueva-reserva/cabanas-tacuifi?unidad=1",
      booking: "https://www.booking.com/Share-VkSF97",
    },
  },

  {
    id: "piedra",
    title: "Cabaña de piedra",
    subtitle: "Hasta 4 personas",
    info: "Cabaña de 50m² construída en una planta. Cuenta con dos dormitorios (1° dormitorio sommier doble - 2° dormitorio dos sommiers simples), baño, cocina-comedor, galería-cochera y asador con parrilla individual.",
    equipment: [
      { name: 'Smart TV 32"', icon: "Tv" },
      { name: "Vajilla completa", icon: "Coffee" },
      { name: "Heladera con congelador", icon: "Refrigerator" },
      { name: "Tender", icon: "Shirt" },
    ],
    folder: "cabana",
    images: [
      "1.jpg",
      "2.jpg",
      "3.jpg",
      "4.jpg",
      "5.jpg",
      "6.jpg",
      "7.jpg",
      "8.jpg",
      "9.jpg",
      "10.jpg",
      "11.jpg",
      "12.jpg",
      "13.jpg",
      "14.jpg",
      "15.jpg",
      "16.jpg",
      "17.jpg",
      "18.jpg",
      "19.jpg",
      "20.jpg",
      "21.jpg",
      "22.jpg",
      "23.jpg",
      "24.jpg",
    ],

    links: {
      turismomax: "https://turismomax.com/nueva-reserva/cabanas-tacuifi?unidad=2",
    },
  },
];
